"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {ArrowUp,BookOpen,Check,LogIn,Menu,MessageSquare,PlusCircle,Settings,Sidebar as SidebarIcon,Trash2,User,X} from "react-feather";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {DEFAULT_SETTINGS, type ChatMessage, type Provider, type Settings as AppSettings} from "../lib/types";
import {readChats,readSettings,writeChats,writeSettings} from "../lib/storage";
import {clearUser,readUser,type ClientUser} from "../lib/oauth";
import {LEARN_MODELS, MODEL_REGISTRY} from "../lib/models";
import type {LearnModel} from "../lib/types";
const labels:Record<Provider,string>={gemini:"Gemini",openai:"OpenAI",anthropic:"Anthropic"};
type Chat={id:string;title:string;messages:ChatMessage[];updatedAt:number};
function mergeSettings():AppSettings{const s=readSettings();return {provider:s.provider||DEFAULT_SETTINGS.provider,model:s.model||DEFAULT_SETTINGS.model,keys:{...DEFAULT_SETTINGS.keys,...s.keys},systemPrompt:s.systemPrompt||DEFAULT_SETTINGS.systemPrompt};}
export default function LearnGPT(){
 const [user,setUser]=useState<ClientUser|null>(null),[settings,setSettings]=useState<AppSettings>(DEFAULT_SETTINGS),[chats,setChats]=useState<Chat[]>([]),[current,setCurrent]=useState<Chat|null>(null),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[sidebarCollapsed,setSidebarCollapsed]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[status,setStatus]=useState("");
 const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{setSettings(mergeSettings());setChats(readChats());setUser(readUser());},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[current?.messages.length,loading]);
 const model=settings.model;
 const persistChats=(next:Chat[])=>{setChats(next);writeChats(next)};
 const newChat=()=>{setCurrent({id:crypto.randomUUID(),title:"New chat",messages:[],updatedAt:Date.now()});setInput("");setMobileOpen(false)};
 const send=async(prompt=input.trim())=>{if(!prompt||loading)return;let chat=current;if(!chat){chat={id:crypto.randomUUID(),title:prompt.slice(0,42),messages:[],updatedAt:Date.now()};setCurrent(chat)}const messages=[...chat.messages,{role:"user" as const,content:prompt}];const nextChat={...chat,title:chat.messages.length?chat.title:prompt.slice(0,42),messages,updatedAt:Date.now()};setCurrent(nextChat);setInput("");setLoading(true);try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider:settings.provider,model,apiKey:settings.keys[settings.provider],systemPrompt:settings.systemPrompt,messages})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Request failed");const finalChat={...nextChat,messages:[...messages,{role:"assistant" as const,content:data.text}],updatedAt:Date.now()};setCurrent(finalChat);persistChats([finalChat,...chats.filter(c=>c.id!==finalChat.id)]);}catch(e){setStatus(e instanceof Error?e.message:"Something went wrong.");}finally{setLoading(false)}};
 const save=()=>{writeSettings(settings);setStatus("Settings saved.");setSettingsOpen(false);setTimeout(()=>setStatus(""),1800)};
 const history=useMemo(()=>chats.filter(c=>c.messages.length),[chats]);
 return <div className={`app ${sidebarCollapsed?"sidebar-is-collapsed":""}`}>
  <aside className={`sidebar ${sidebarCollapsed?"collapsed":""} ${mobileOpen?"open":""}`}><div className="brand-row"><a className="brand" href="/"><BookOpen size={23}/><span>LearnGPT</span></a><button className="icon-btn sidebar-close" aria-label="Close sidebar" onClick={()=>setMobileOpen(false)}><X size={18}/></button></div><button className="new-chat" onClick={newChat}><PlusCircle size={18}/>New chat</button><div className="history-title">History</div><div className="history">{history.length?history.map(c=><button className={`history-item ${current?.id===c.id?"active":""}`} key={c.id} onClick={()=>{setCurrent(c);setMobileOpen(false)}}><MessageSquare size={15}/><span>{c.title}</span></button>):<div style={{color:"var(--muted)",fontSize:12,padding:10,lineHeight:1.6}}>No conversations yet.</div>}</div><div className="account"><div className="avatar">{user?.avatar?<img src={user.avatar} alt=""/>:<User size={17}/>}</div><div className="account-info"><div className="account-name">{user?.name||"Guest mode"}</div><div className="account-email">{user?.email||"Local session"}</div></div><button className="icon-btn" title={user?"Sign out":"Login"} onClick={()=>{if(user){clearUser();setUser(null)}else location.href="/auth/login"}}>{user?<LogIn size={17}/>:<LogIn size={17}/>}</button></div><button className="new-chat" style={{marginTop:10}} onClick={()=>{localStorage.removeItem("learngpt.chats");setChats([]);setCurrent(null)}}><Trash2 size={17}/>Clear history</button></aside>
  <main className="main"><header className="topbar"><div className="topbar-left"><button className="icon-btn sidebar-toggle" aria-label={sidebarCollapsed?"Open sidebar":"Collapse sidebar"} onClick={()=>setSidebarCollapsed(v=>!v)}><SidebarIcon size={19}/></button><button className="icon-btn mobile-menu" aria-label="Open sidebar" onClick={()=>setMobileOpen(true)}><Menu size={19}/></button><div className="model-picker"><span className="pill">{labels[settings.provider]}</span><select value={model} onChange={e=>setSettings(s=>({...s,model:e.target.value as LearnModel}))}>{LEARN_MODELS.map(m=><option key={m} value={m}>{m}</option>)}</select></div></div><div className="topbar-right"><button className="icon-btn" onClick={()=>setSettingsOpen(true)}><Settings size={18}/></button></div></header>
   <section className="chat"><div className="messages">{!current?.messages.length?<div className="welcome"><div className="welcome-logo"><BookOpen size={30}/></div><h1>How can I help you learn?</h1><p>LearnGPT is your multi-provider learning assistant. Choose Gemini, OpenAI, or Anthropic in Settings and start learning.</p><div className="suggestions"><button className="suggestion" onClick={()=>send("Teach me JavaScript variables from the basics with a simple example.")}><b>Learn a concept</b><span>Start from zero with a guided explanation.</span></button><button className="suggestion" onClick={()=>send("Quiz me on HTML and CSS with 5 questions, one at a time.")}><b>Practice</b><span>Turn a topic into an interactive quiz.</span></button><button className="suggestion" onClick={()=>send("Help me make a 30-minute study plan for learning JavaScript tonight.")}><b>Make a plan</b><span>Build a realistic study session.</span></button></div></div>:current.messages.map((m,i)=><div className={`message ${m.role}`} key={i}><div className="message-icon">{m.role==="user"?<User size={16}/>:<BookOpen size={16}/>}</div><div><div className="bubble markdown"><ReactMarkdown remarkPlugins={[remarkGfm]}>{m.content}</ReactMarkdown></div><div className="meta">{m.role==="user"?"You":labels[settings.provider]}</div></div></div>)}{loading&&<div className="message assistant"><div className="message-icon"><BookOpen size={16}/></div><div><div className="bubble markdown thinking">Thinking…</div><div className="meta">{labels[settings.provider]}</div></div></div>}<div ref={bottom}/></div><div className="composer-wrap"><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message LearnGPT…" rows={1}/><button className="send" disabled={loading||!input.trim()} onClick={()=>send()}><ArrowUp size={19}/></button></div><div className="disclaimer">API keys are kept in this browser and sent only to your selected provider through the LearnGPT API route.</div></div></section>
  </main>
  {settingsOpen&&<div className="overlay"><div className="modal"><div className="modal-head"><div><h2>API Settings</h2><p style={{color:"var(--muted)",fontSize:12}}>Gemini is the default provider.</p></div><button className="icon-btn" onClick={()=>setSettingsOpen(false)}><X size={18}/></button></div><div className="field"><label>Provider</label><select value={settings.provider} onChange={e=>setSettings(s=>({...s,provider:e.target.value as Provider}))}><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option></select></div><div className="field"><label>LearnGPT Model</label><select value={settings.model} onChange={e=>setSettings(s=>({...s,model:e.target.value as LearnModel}))}>{LEARN_MODELS.map(m=><option key={m} value={m}>{m}</option>)}</select><div style={{color:"var(--muted)",fontSize:12,marginTop:7}}>API model: <code>{MODEL_REGISTRY[settings.provider][settings.model]}</code></div></div>{(["gemini","openai","anthropic"] as Provider[]).map(p=><div className="field" key={p}><label>{labels[p]} API Key</label><input type="password" autoComplete="off" value={settings.keys[p]} onChange={e=>setSettings(s=>({...s,keys:{...s.keys,[p]:e.target.value}}))} placeholder="Enter API key"/></div>)}<div className="field"><label>Learning instructions</label><textarea rows={5} value={settings.systemPrompt} onChange={e=>setSettings(s=>({...s,systemPrompt:e.target.value}))}/></div>{status&&<div className="status ok"><Check size={14} style={{verticalAlign:"middle",marginRight:5}}/>{status}</div>}<div className="actions"><button className="btn" onClick={()=>setSettingsOpen(false)}>Cancel</button><button className="btn primary" onClick={save}>Save settings</button></div></div></div>}
 </div>
}
