"use client";
import Script from "next/script";
import {useEffect,useRef,useState} from "react";
import {BookOpen,GitHub,ArrowLeft,Loader} from "react-feather";
import {pkce,randomState,readUser,saveUser,type ClientUser} from "../../../lib/oauth";

declare global {interface Window{google?:any}}
function decodeJwt(token:string){const payload=token.split(".")[1];return JSON.parse(atob(payload.replace(/-/g,"+").replace(/_/g,"/")));}
export default function LoginPage(){
 const googleRef=useRef<HTMLDivElement>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{const u=readUser();if(u) location.href="/";},[]);
 useEffect(()=>{const code=new URLSearchParams(location.search).get("code");const state=new URLSearchParams(location.search).get("state");const saved=localStorage.getItem("learngpt.github.state");const verifier=localStorage.getItem("learngpt.github.verifier");if(code&&state&&saved===state&&verifier)exchangeGithub(code,verifier);},[]);
 useEffect(()=>{if(!window.google||!googleRef.current||!process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID)return;window.google.accounts.id.initialize({client_id:process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,callback:(response:any)=>{try{const p=decodeJwt(response.credential);const user:ClientUser={provider:"google",id:p.sub,name:p.name||p.email,email:p.email,avatar:p.picture};saveUser(user);location.href="/";}catch{setError("Google sign-in response could not be read.")}}});window.google.accounts.id.renderButton(googleRef.current,{theme:"filled_black",size:"large",shape:"rectangular",width:320,text:"signin_with"});},[]);
 async function exchangeGithub(code:string,verifier:string){setLoading(true);try{const r=await fetch("https://github.com/login/oauth/access_token",{method:"POST",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify({client_id:process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID,code,code_verifier:verifier,redirect_uri:location.origin+"/auth/login"})});const token=await r.json();if(!token.access_token)throw new Error(token.error_description||"GitHub authorization failed.");const me=await fetch("https://api.github.com/user",{headers:{Authorization:`Bearer ${token.access_token}`,Accept:"application/vnd.github+json"}}).then(x=>x.json());const emails=me.email?null:await fetch("https://api.github.com/user/emails",{headers:{Authorization:`Bearer ${token.access_token}`,Accept:"application/vnd.github+json"}}).then(x=>x.json());const primary=me.email||(Array.isArray(emails)?emails.find((e:any)=>e.primary)?.email:undefined);saveUser({provider:"github",id:String(me.id),name:me.name||me.login,email:primary,avatar:me.avatar_url});localStorage.removeItem("learngpt.github.state");localStorage.removeItem("learngpt.github.verifier");history.replaceState({},"","/auth/login");location.href="/";}catch(e){setError(e instanceof Error?e.message:"GitHub sign-in failed.");}finally{setLoading(false)}}
 async function github(){setError("");if(!process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID){setError("Set NEXT_PUBLIC_GITHUB_CLIENT_ID in .env.local first.");return}const state=randomState();const {verifier,challenge}=await pkce();localStorage.setItem("learngpt.github.state",state);localStorage.setItem("learngpt.github.verifier",verifier);const q=new URLSearchParams({client_id:process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID,redirect_uri:location.origin+"/auth/login",scope:"read:user user:email",state,code_challenge:challenge,code_challenge_method:"S256"});location.href=`https://github.com/login/oauth/authorize?${q}`;}
 return <><Script src="https://accounts.google.com/gsi/client" strategy="afterInteractive"/><main className="login-page"><div className="login-card"><a className="back" href="/"><ArrowLeft size={16}/>Back to LearnGPT</a><div className="login-brand"><BookOpen size={30}/><span>LearnGPT</span></div><h1>Welcome back</h1><p>Sign in to keep your learning profile on this browser.</p><div ref={googleRef} className="google-button"/><button className="oauth-btn github" onClick={github} disabled={loading}><GitHub size={18}/>{loading?<><Loader size={16} className="spin"/>Signing in…</>:"Continue with GitHub"}</button>{error&&<div className="status error">{error}</div>}<small>Client-only authentication. No Firebase is used.</small></div></main></>;
}
